apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-default
spec:
  destination:
    name: helloworld
  route:
  - labels:
      version: v1
  httpReqTimeout:
    simpleTimeout:
      timeout: 10000000s
  httpReqRetries:
    simpleRetry:
      perTryTimeout: 1000s
      attempts: 9999999

