apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: pwave-retry
spec:
  destination:
    name: helloworld
  route:
  - labels:
      version: v1
  httpReqRetries:
    simpleRetry:
      perTryTimeout: 1000s
      attempts: 100000

