apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pwave-cloud
  labels:
    app: pwave-cloud
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pwave-cloud
    spec:
      containers:
      - image: gcr.io/pwave-cloud/github-toeplitz-pwave-cloud:d6e6893289a3bfe67f49fcd8e41fde4a98c3d475
        name: pwave-cloud
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
         - name: http
           containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: pwave-cloud
  labels:
    app: pwave-cloud
spec:
  ports:
  - nodePort: 30080
    port: 50051
    protocol: TCP
    targetPort: 50051    
  selector:
    app: pwave-cloud
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}   
