apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pwave-cloud
  labels:
    app: pwave-cloud
spec:
#  replicas: 50
  template:
    metadata:
      labels:
        app: pwave-cloud
    spec:
      containers:
      - image: gcr.io/pwave-cloud/github-toeplitz-pwave-cloud:22ee3220248c8f924cfb6696ee102f70eab77197
        name: pwave-cloud
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
         - name: http
           containerPort: 50051
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pwave-cloud
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: pwave-cloud
    spec:
      containers:
      - name: pwave-cloud
        image: gcr.io/pwave-cloud/github-toeplitz-pwave-cloud:41606dbec435edcd252d74e0d28248fd6041e9a1
        ports:
        - containerPort: 50051
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pwave-cloud
  namespace: default
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: pwave-cloud
---
apiVersion: v1
kind: Service
metadata:
  name: pwave-cloud
  labels:
    app: pwave-cloud
spec:
  ports:
  - nodePort: 30080
    port: 50051
    protocol: TCP
    targetPort: 50051    
  selector:
    app: pwave-cloud
  #sessionAffinity: None
  type: NodePort
#status:
#  loadBalancer: {}   
