apiVersion: v1
kind: Service
metadata:
  name: pwave-cloud
  labels:
    app: pwave-cloud
spec:
  type: NodePort
  ports:
  - port: 50051
    # This port needs to be available on all nodes in the cluster
    nodePort: 30301
    targetPort: 50051
    protocol: TCP
    name: http
  selector:
    app: pwave-cloud
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pwave-cloud
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pwave-cloud
    spec:
      containers:
      - name: pwave-cloud
        image: gcr.io/pwave-cloud/github-toeplitz-pwave-cloud:6cc63aed4e6aa7cef3f352cd0769f7c273a37d48
        ports:
        - containerPort: 50051
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
#  loadBalancer: {}   
